apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - image: sahild42770/rabbitmq
        name: rabbitmq-cont
        ports:
        - containerPort: 15672
        env:
        - name: "RABBITMQ_DEFAULT_USER"
          value: "test"
        - name: "RABBITMQ_DEFAULT_PASS"
          value: "test"